[bar/top]
enable-ipc = true
override-redirect = false

bottom = false
height = 30
fixed-center = true
width = 100%
; offset-x = 1%
; offset-y = 1%

radius = 10

padding = 0 

module-margin-left = 1
module-margin-right = 1

dim-value = 1

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1

sep = " "

font-0 = ${fonts.awesome}
font-1 = ${fonts.fira}

wm-restack = bspwm
tray-position = left

modules-left = dmenu music title
modules-center = date clock
modules-right = tempicon temperature memory customcpu cpu battery sound bluetooth wifi


